name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Maven settings
      run: |
        mkdir -p ~/.m2
        echo "<settings><servers><server><id>github</id><username>${{ secrets.CUSTOM_GITHUB_ACTOR }}</username><password>${{ secrets.CUSTOM_GITHUB_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

    - name: Build and deploy
      run: mvn clean deploy
